dns:
  enable: true
  # listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fallback:
    - tls://8.8.4.4
    - tls://1.1.1.1
    - https://dns.google/dns-query

rule-providers:
  MainlandNetwork:
    type: http
    url: https://fastly.jsdelivr.net/gh/eric-gitta-moore/sub-rules-provider@main/rule/james-curtis/Clash/Providers/MainlandNetwork.yaml
    proxy: DIRECT
    behavior: classical
  AboardNetwork:
    type: http
    url: https://fastly.jsdelivr.net/gh/eric-gitta-moore/sub-rules-provider@main/rule/james-curtis/Clash/Providers/AboardNetwork.yaml
    proxy: DIRECT
    behavior: classical
  CompanyNetwork:
    type: http
    url: https://fastly.jsdelivr.net/gh/eric-gitta-moore/sub-rules-provider@main/rule/james-curtis/Clash/Providers/CompanyNetwork.yaml
    proxy: DIRECT
    behavior: classical

rules:
  - GEOSITE,private,DIRECT
  - GEOIP,private,DIRECT,no-resolve

  - RULE-SET,CompanyNetwork,公司网络,no-resolve
  - RULE-SET,AboardNetwork,出国,no-resolve
  - RULE-SET,MainlandNetwork,DIRECT,no-resolve

  - GEOSITE,cn,DIRECT
  - GEOIP,cn,DIRECT,no-resolve

  - AND,(DST-PORT,443),(NETWORK,UDP),REJECT # quic
  - MATCH,出国


proxy-groups:
  - { name: 出国, type: select, proxies: [ 自动选择, 手动选择, DIRECT ] }
  - { name: 自动选择, type: url-test, use: [ provider1 ], url: https://support.google.com }
  - { name: 手动选择, type: select, use: [ provider1 ] }



proxy-providers:
  provider1:
    type: http
    url: http://test.com
    interval: 86400
    proxy: DIRECT
    health-check:
      enable: true
      url: https://support.google.com
