dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  default-nameserver:
    - 223.5.5.5 # aliyun
    - 119.29.29.29 # tencent
    - 101.226.4.6 # 360

  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.360.cn/dns-query
    - https://doh.pub/dns-query
  fallback:
    - tls://8.8.4.4
    - tls://1.1.1.1
    - https://dns.google/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true

rule-providers:
  MainlandNetwork:
    type: http
    url: https://fastly.jsdelivr.net/gh/eric-gitta-moore/sub-rules-provider@main/rule/james-curtis/Clash/Providers/MainlandNetwork.yaml
    proxy: DIRECT
    behavior: classical
  AboardNetwork:
    type: http
    url: https://fastly.jsdelivr.net/gh/eric-gitta-moore/sub-rules-provider@main/rule/james-curtis/Clash/Providers/AboardNetwork.yaml
    proxy: DIRECT
    behavior: classical

rules:
  - GEOSITE,private,DIRECT
  - GEOIP,private,DIRECT,no-resolve

  - RULE-SET,AboardNetwork,出国,no-resolve
  - RULE-SET,MainlandNetwork,DIRECT,no-resolve

  - GEOSITE,cn,DIRECT
  - GEOIP,cn,DIRECT,no-resolve

  - AND,(DST-PORT,443),(NETWORK,UDP),REJECT # quic
  - MATCH,出国


proxy-groups:
  - { name: 出国, type: select, proxies: [ 自动选择, 手动选择, DIRECT ] }
  - { name: 自动选择, type: url-test, use: [ provider1 ], url: https://support.google.com, interval: 86400, timeout: 3000 }
  - { name: 手动选择, type: select, use: [ provider1 ] }



proxy-providers:
  provider1:
    type: http
    url: http://test.com
    interval: 86400
    proxy: DIRECT
    health-check:
      enable: true
      url: https://support.google.com
      interval: 86400
      timeout: 3000