log:
  level: info
  timestamp: true


dns:
  servers:
    - { tag: remote, address: tcp://8.8.8.8, detour: 默认 }
    - { tag: local, address: 223.5.5.5, detour: DIRECT }
  rules:
    - { server: local, rule_set: [ GeoSite@tld-cn, GeoSite@cn ] }
    - { server: local, outbound: [ any ] }


inbounds:
  - type: mixed
    tag: mixed-in
    listen: 127.0.0.1
    listen_port: 2080
    sniff: true
    sniff_override_destination: true
    domain_strategy: prefer_ipv4


route:
  final: 默认
  auto_detect_interface: true
  rule_set:
    - { tag: AboardNetwork, download_detour: 自动选择, type: remote, format: source, url: https://raw.githubusercontent.com/eric-gitta-moore/sub-diversion-rules/main/rule/james-curtis/Clash/Providers/AboardNetwork.json }
    - { tag: MainlandNetwork, download_detour: 自动选择, type: remote, format: source, url: https://raw.githubusercontent.com/eric-gitta-moore/sub-diversion-rules/main/rule/james-curtis/Clash/Providers/MainlandNetwork.json }
    - { tag: GoogleOneVPNTun, download_detour: 自动选择, type: remote, format: source, url: https://raw.githubusercontent.com/eric-gitta-moore/sub-diversion-rules/main/rule/james-curtis/Clash/Providers/GoogleOneVPNTun.json }
    - { tag: GoogleOneVPNCheckPoint, download_detour: 自动选择, type: remote, format: source, url: https://raw.githubusercontent.com/eric-gitta-moore/sub-diversion-rules/main/rule/james-curtis/Clash/Providers/GoogleOneVPNCheckPoint.json }
    # 系统规则 begin
    - { tag: GeoSite@tld-cn, download_detour: 自动选择, type: remote, format: binary, url: https://raw.githubusercontent.com/eric-gitta-moore/meta-rules-dat/sing/geo/geosite/tld-cn.srs }
    - { tag: GeoSite@cn, download_detour: 自动选择, type: remote, format: binary, url: https://raw.githubusercontent.com/eric-gitta-moore/meta-rules-dat/sing/geo/geosite/cn.srs }

    - { tag: GeoIP@cn, download_detour: 自动选择, type: remote, format: binary, url: https://raw.githubusercontent.com/eric-gitta-moore/meta-rules-dat/sing/geo/geoip/cn.srs }
    - { tag: GeoIP@private, download_detour: 自动选择, type: remote, format: binary, url: https://raw.githubusercontent.com/eric-gitta-moore/meta-rules-dat/sing/geo/geoip/private.srs }
    - { tag: GeoSite@private, download_detour: 自动选择, type: remote, format: binary, url: https://raw.githubusercontent.com/eric-gitta-moore/meta-rules-dat/sing/geo/geosite/private.srs }
  # 系统规则 end

  rules:
    - { outbound: dns-out, protocol: dns }

    - { outbound: GoogleOneVPNCheckPoint, rule_set: [ GoogleOneVPNCheckPoint ] }
    - { outbound: GoogleOneVPNTun, rule_set: [ GoogleOneVPNTun ] }

    - { outbound: 国内, rule_set: [ GeoSite@private, MainlandNetwork ] }
    - { outbound: 默认, rule_set: [ AboardNetwork ] }
    - { outbound: 国内, rule_set: [ GeoSite@tld-cn, GeoSite@cn, GeoIP@cn, GeoIP@private ] }


experimental:
  cache_file: { enabled: true }
  clash_api: { external_controller: 127.0.0.1:9090 }


outbounds:
  - { tag: 默认, type: selector, outbounds: [ 自动选择, 手动选择, DIRECT ], interrupt_exist_connections: true }
  - { tag: 自动选择, type: urltest, include-all: true, filter: '^(?!.*(?:(中国|CN))).*', interrupt_exist_connections: true, url: https://www.youtube.com/generate_204, interval: 6h, idle_timeout: 12h }
  - { tag: 手动选择, type: selector, include-all: true, interrupt_exist_connections: true }
  - { tag: 前置代理组, type: selector, include-all-providers: true, interrupt_exist_connections: true }
  - { tag: GoogleOneVPNCheckPoint, outbounds: [ 默认, 自动选择, 手动选择, DIRECT ], type: selector, interrupt_exist_connections: true }
  - { tag: GoogleOneVPNTun, outbounds: [ 默认, 自动选择, 手动选择, DIRECT ], type: selector, interrupt_exist_connections: true }
  - { tag: 国内, outbounds: [ DIRECT, 默认, 自动选择, 手动选择 ], type: selector, interrupt_exist_connections: true }

  - { tag: DIRECT, type: direct }
  - { tag: dns-out, type: dns }

custom_outbounds:
  - tag: G1 ss detour
    type: shadowsocks
    server: 149.104.24.100
    server_port: 10001
    method: chacha20-ietf-poly1305
    password: aaf0cc77-ec05-4b5e-8fbb-8919c3aecf8c
    multiplex: { enabled: true }
    detour: 前置代理组
