log:
  level: debug
  timestamp: true


dns:
  final: dns_direct
  independent_cache: true
  strategy: ipv4_only
  servers:
    - {tag: dns_direct, address: h3://dns.alidns.com/dns-query, address_resolver: dns_resolver, detour: DIRECT}
    - {tag: dns_proxy, address: tls://1.1.1.1, address_resolver: dns_resolver}
    - {tag: dns_resolver, address: 223.5.5.5, detour: DIRECT}
  rules:
    - {outbound: [any], server: dns_resolver}
    - {rule_set: [GeoSite@geolocation-!cn, GeoSite@gfw, GeoSite@tld-!cn], server: dns_proxy}
    - {clash_mode: global, server: dns_proxy}
    - {clash_mode: direct, server: dns_resolver}

ntp:
  enabled: true
  server: time.apple.com
  server_port: 123
  interval: 30m
  detour: DIRECT


inbounds:
  - type: mixed
    tag: mixed-in
    listen: 0.0.0.0
    listen_port: 2080


route:
  final: 漏网之鱼
  auto_detect_interface: true
  rule_set:
    - {tag: AboardNetwork, type: remote, format: source, url: https://raw.githubusercontent.com/james-curtis/sub-diversion-rules/main/rule/james-curtis/Clash/Providers/AboardNetwork.json}
    - {tag: GeoSite@tiktok, type: remote, format: binary, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/tiktok.srs}
    - {tag: GeoSite@openai, type: remote, format: binary, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/openai.srs}
    - {tag: GeoSite@Claude, type: remote, format: binary, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/bm7/Claude.srs}
    - {tag: GeoSite@Gemini, type: remote, format: binary, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/bm7/Gemini.srs}
    # 系统规则 begin
    - {tag: GeoSite@category-dev-cn, type: remote, format: binary, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/category-dev-cn.srs}
    - {tag: GeoSite@category-scholar-cn, type: remote, format: binary, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/category-scholar-cn.srs}
    - {tag: GeoSite@category-games@cn, type: remote, format: binary, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/category-games@cn.srs}
    - {tag: GeoSite@google@cn, type: remote, format: binary, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/google@cn.srs}
    - {tag: GeoSite@tld-cn, type: remote, format: binary, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/tld-cn.srs}
    - {tag: GeoSite@cn, type: remote, format: binary, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/cn.srs}

    - {tag: GeoSite@apple, type: remote, format: binary, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/apple.srs}
    - {tag: GeoSite@zoom, type: remote, format: binary, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/zoom.srs}
    - {tag: GeoSite@google, type: remote, format: binary, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/google.srs}
    - {tag: GeoSite@meta, type: remote, format: binary, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/meta.srs}
    - {tag: GeoSite@category-games, type: remote, format: binary, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/category-games.srs}

    - {tag: GeoSite@category-social-media-!cn, type: remote, format: binary, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/category-social-media-!cn.srs}
    - {tag: GeoSite@category-porn, type: remote, format: binary, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/category-porn.srs}
    - {tag: GeoSite@category-communication, type: remote, format: binary, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/category-communication.srs}
    - {tag: GeoSite@category-dev, type: remote, format: binary, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/category-dev.srs}

    - {tag: GeoSite@tld-!cn, type: remote, format: binary, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/tld-!cn.srs}
    - {tag: GeoSite@gfw, type: remote, format: binary, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/gfw.srs}
    - {tag: GeoSite@geolocation-!cn, type: remote, format: binary, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/geolocation-!cn.srs}

    - {tag: GeoIP@google, type: remote, format: binary, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geoip/google.srs}
    - {tag: GeoIP@cn, type: remote, format: binary, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geoip/cn.srs}
    - {tag: GeoMixed@private, type: remote, format: binary, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/mixed/private.srs}
  # 系统规则 end

  rules:
    - {outbound: dns-out, protocol: dns}
    - {clash_mode: direct, outbound: DIRECT}
    - {clash_mode: global, outbound: 默认}

    - {outbound: DIRECT, rule_set: [GeoMixed@private]}
    - {outbound: 国内, rule_set: [GeoSite@category-dev-cn, GeoSite@category-scholar-cn, GeoSite@category-games@cn, GeoSite@google@cn, GeoSite@tld-cn, GeoSite@cn, GeoIP@cn]}
    - {outbound: Apple, rule_set: [GeoSite@apple]}
    - {outbound: LLM, rule_set: [GeoSite@openai, GeoSite@Claude, GeoSite@Gemini]}
    - {outbound: Zoom, rule_set: [GeoSite@zoom]}
    - {outbound: Google, rule_set: [GeoSite@google, GeoIP@google]}
    - {outbound: 漏网之鱼, rule_set: [AboardNetwork, GeoSite@tiktok, GeoSite@meta, GeoSite@category-games, GeoSite@category-social-media-!cn, GeoSite@category-porn, GeoSite@category-communication, GeoSite@category-dev, GeoSite@tld-!cn, GeoSite@gfw, GeoSite@geolocation-!cn]}


experimental:
  cache_file:
    enabled: true


outbounds:
  - {tag: 默认, type: selector, outbounds: [自动选择, 手动选择1, 手动选择2, 手动选择3, 香港节点, 台湾节点, 日本节点, 新加坡节点, 美国节点, DIRECT]}
  - {tag: 自动选择, type: urltest, include-all: true, filter: '^(?!.*(?:(中国|CN))).*'}
  - {tag: '⭕⭕====分割线 1====⭕⭕', type: selector, outbounds: [DIRECT]}
  - {tag: 手动选择1, type: selector, outbounds: [自动选择, 香港节点, 台湾节点, 日本节点, 新加坡节点, 美国节点, DIRECT]}
  - {tag: 手动选择2, type: selector, include-all: true}
  - {tag: 手动选择3, type: selector, include-all: true}
  - {tag: 前置代理组, type: selector, include-all-providers: true}
  - {tag: '⭕⭕====分割线 2====⭕⭕', type: selector, outbounds: [DIRECT]}
  - {tag: Google, outbounds: [默认, 香港节点, 台湾节点, 日本节点, 新加坡节点, 美国节点, 手动选择1, 手动选择2, 手动选择3, 自动选择, DIRECT], type: selector}
  - {tag: Zoom, outbounds: [默认, 香港节点, 台湾节点, 日本节点, 新加坡节点, 美国节点, 手动选择1, 手动选择2, 手动选择3, 自动选择, DIRECT], type: selector}
  - {tag: Apple, outbounds: [DIRECT, 默认, 香港节点, 台湾节点, 日本节点, 新加坡节点, 美国节点, 手动选择1, 手动选择2, 手动选择3, 自动选择], type: selector}
  - {tag: LLM, outbounds: [默认, 香港节点, 台湾节点, 日本节点, 新加坡节点, 美国节点, 手动选择1, 手动选择2, 手动选择3, 自动选择, DIRECT], type: selector}
  - {tag: '⭕⭕====分割线 3====⭕⭕', type: selector, outbounds: [DIRECT]}
  - {tag: 香港节点, type: urltest, include-all-providers: true, filter: '(香港)'}
  - {tag: 台湾节点, type: urltest, include-all-providers: true, filter: '(台湾)'}
  - {tag: 日本节点, type: urltest, include-all-providers: true, filter: '(日本)'}
  - {tag: 新加坡节点, type: urltest, include-all-providers: true, filter: '(新加坡)'}
  - {tag: 美国节点, type: urltest, include-all-providers: true, filter: '美|us|unitedstates|united states'}
  - {tag: '⭕⭕====分割线 4====⭕⭕', type: selector, outbounds: [DIRECT]}
  - {tag: 国内, outbounds: [DIRECT, 默认, 香港节点, 台湾节点, 日本节点, 新加坡节点, 美国节点, 手动选择1, 手动选择2, 手动选择3, 自动选择], type: selector}
  - {tag: 漏网之鱼, outbounds: [默认, 香港节点, 台湾节点, 日本节点, 新加坡节点, 美国节点, 手动选择1, 手动选择2, 手动选择3, 自动选择, DIRECT], type: selector}

  - {tag: DIRECT, type: direct}
  - {tag: dns-out, type: dns}

custom_outbounds:
  - tag: G1 ss
    type: shadowsocks
    server: 149.104.24.100
    server_port: 10001
    method: chacha20-ietf-poly1305
    password: aaf0cc77-ec05-4b5e-8fbb-8919c3aecf8c
    multiplex:
      enabled: true
