log:
  level: info
  timestamp: true


dns:
  final: dns_proxy
  independent_cache: true
  strategy: prefer_ipv4
  servers:
    - { tag: dns_proxy, address: 8.8.8.8, detour: 默认 }
    - { tag: dns_resolver, address: 223.5.5.5, detour: DIRECT }
  rules:
    - { outbound: [ any ], server: dns_resolver }
    #    - { rule_set: [ GeoSite@geolocation-!cn, GeoSite@gfw, GeoSite@tld-!cn ], server: dns_proxy }
    - { rule_set: [ GeoSite@cn, GeoSite@tld-cn ], server: dns_resolver }


inbounds:
  - type: mixed
    tag: mixed-in
    listen: 0.0.0.0
    listen_port: 2080
    sniff: true
    sniff_override_destination: true
    domain_strategy: prefer_ipv4


route:
  final: 默认
  auto_detect_interface: true
  rule_set:
    - { tag: AboardNetwork, type: remote, format: source, url: https://jihulab.com/james-curtis/sub-diversion-rules/-/raw/main/rule/james-curtis/Clash/Providers/AboardNetwork.json }
    - { tag: GoogleOneVPNTun, type: remote, format: source, url: https://jihulab.com/james-curtis/sub-diversion-rules/-/raw/main/rule/james-curtis/Clash/Providers/GoogleOneVPNTun.json }
    - { tag: GoogleOneVPNCheckPoint, type: remote, format: source, url: https://jihulab.com/james-curtis/sub-diversion-rules/-/raw/main/rule/james-curtis/Clash/Providers/GoogleOneVPNCheckPoint.json }
    # 系统规则 begin
    - { tag: GeoSite@category-dev-cn, type: remote, format: binary, url: https://jihulab.com/james-curtis/meta-rules-dat/-/raw/sing/geo/geosite/category-dev-cn.srs }
    - { tag: GeoSite@category-scholar-cn, type: remote, format: binary, url: https://jihulab.com/james-curtis/meta-rules-dat/-/raw/sing/geo/geosite/category-scholar-cn.srs }
    - { tag: GeoSite@category-games@cn, type: remote, format: binary, url: https://jihulab.com/james-curtis/meta-rules-dat/-/raw/sing/geo/geosite/category-games@cn.srs }
    - { tag: GeoSite@tld-cn, type: remote, format: binary, url: https://jihulab.com/james-curtis/meta-rules-dat/-/raw/sing/geo/geosite/tld-cn.srs }
    - { tag: GeoSite@cn, type: remote, format: binary, url: https://jihulab.com/james-curtis/meta-rules-dat/-/raw/sing/geo/geosite/cn.srs }

    - { tag: GeoSite@apple, type: remote, format: binary, url: https://jihulab.com/james-curtis/meta-rules-dat/-/raw/sing/geo/geosite/apple.srs }
    - { tag: GeoSite@zoom, type: remote, format: binary, url: https://jihulab.com/james-curtis/meta-rules-dat/-/raw/sing/geo/geosite/zoom.srs }
    - { tag: GeoSite@google, type: remote, format: binary, url: https://jihulab.com/james-curtis/meta-rules-dat/-/raw/sing/geo/geosite/google.srs }
    - { tag: GeoSite@github, type: remote, format: binary, url: https://jihulab.com/james-curtis/meta-rules-dat/-/raw/sing/geo/geosite/github.srs }
    - { tag: GeoSite@microsoft, type: remote, format: binary, url: https://jihulab.com/james-curtis/meta-rules-dat/-/raw/sing/geo/geosite/microsoft.srs }
    - { tag: GeoSite@microsoft@cn, type: remote, format: binary, url: https://jihulab.com/james-curtis/meta-rules-dat/-/raw/sing/geo/geosite/microsoft@cn.srs }
    - { tag: GeoSite@imgur, type: remote, format: binary, url: https://jihulab.com/james-curtis/meta-rules-dat/-/raw/sing/geo/geosite/imgur.srs }
    - { tag: GeoSite@meta, type: remote, format: binary, url: https://jihulab.com/james-curtis/meta-rules-dat/-/raw/sing/geo/geosite/meta.srs }
    - { tag: GeoSite@tiktok, type: remote, format: binary, url: https://jihulab.com/james-curtis/meta-rules-dat/-/raw/sing/geo/geosite/tiktok.srs }
    - { tag: GeoSite@openai, type: remote, format: binary, url: https://jihulab.com/james-curtis/meta-rules-dat/-/raw/sing/geo/geosite/openai.srs }
    - { tag: GeoSite@Claude, type: remote, format: binary, url: https://jihulab.com/james-curtis/meta-rules-dat/-/raw/sing/bm7/Claude.srs }
    - { tag: GeoSite@Gemini, type: remote, format: binary, url: https://jihulab.com/james-curtis/meta-rules-dat/-/raw/sing/bm7/Gemini.srs }

    - { tag: GeoSite@category-games, type: remote, format: binary, url: https://jihulab.com/james-curtis/meta-rules-dat/-/raw/sing/geo/geosite/category-games.srs }
    - { tag: GeoSite@category-social-media-!cn, type: remote, format: binary, url: https://jihulab.com/james-curtis/meta-rules-dat/-/raw/sing/geo/geosite/category-social-media-!cn.srs }
    - { tag: GeoSite@category-porn, type: remote, format: binary, url: https://jihulab.com/james-curtis/meta-rules-dat/-/raw/sing/geo/geosite/category-porn.srs }
    - { tag: GeoSite@category-communication, type: remote, format: binary, url: https://jihulab.com/james-curtis/meta-rules-dat/-/raw/sing/geo/geosite/category-communication.srs }
    - { tag: GeoSite@category-dev, type: remote, format: binary, url: https://jihulab.com/james-curtis/meta-rules-dat/-/raw/sing/geo/geosite/category-dev.srs }
    - { tag: GeoSite@category-anticensorship, type: remote, format: binary, url: https://jihulab.com/james-curtis/meta-rules-dat/-/raw/sing/geo/geosite/category-anticensorship.srs }

    - { tag: GeoSite@tld-!cn, type: remote, format: binary, url: https://jihulab.com/james-curtis/meta-rules-dat/-/raw/sing/geo/geosite/tld-!cn.srs }
    - { tag: GeoSite@gfw, type: remote, format: binary, url: https://jihulab.com/james-curtis/meta-rules-dat/-/raw/sing/geo/geosite/gfw.srs }
    - { tag: GeoSite@geolocation-!cn, type: remote, format: binary, url: https://jihulab.com/james-curtis/meta-rules-dat/-/raw/sing/geo/geosite/geolocation-!cn.srs }

    - { tag: GeoIP@google, type: remote, format: binary, url: https://jihulab.com/james-curtis/meta-rules-dat/-/raw/sing/geo/geoip/google.srs }
    - { tag: GeoIP@cn, type: remote, format: binary, url: https://jihulab.com/james-curtis/meta-rules-dat/-/raw/sing/geo/geoip/cn.srs }
    - { tag: GeoIP@private, type: remote, format: binary, url: https://jihulab.com/james-curtis/meta-rules-dat/-/raw/sing/geo/geoip/private.srs }
    - { tag: GeoSite@private, type: remote, format: binary, url: https://jihulab.com/james-curtis/meta-rules-dat/-/raw/sing/geo/geosite/private.srs }
  # 系统规则 end

  rules:
    - { outbound: dns-out, protocol: dns }

    - { outbound: DIRECT, rule_set: [ GeoSite@private ] }
    - { outbound: 默认, rule_set: [ AboardNetwork ] }
    - { outbound: GoogleOneVPNCheckPoint, rule_set: [ GoogleOneVPNCheckPoint ] }
    - { outbound: GoogleOneVPNTun, rule_set: [ GoogleOneVPNTun ] }

    - { outbound: 国内, rule_set: [ GeoSite@microsoft@cn, GeoSite@category-dev-cn, GeoSite@category-scholar-cn, GeoSite@category-games@cn ] }
    - { outbound: Apple, rule_set: [ GeoSite@apple ] }
    - { outbound: LLM, rule_set: [ GeoSite@openai, GeoSite@Claude, GeoSite@Gemini ] }
    - { outbound: Zoom, rule_set: [ GeoSite@zoom ] }
    - { outbound: Dev, rule_set: [ GeoSite@github ] }
    - { outbound: Google, rule_set: [ GeoSite@google ] }
    - { outbound: Microsoft, rule_set: [ GeoSite@microsoft ] }
    - { outbound: 国外图床, rule_set: [ GeoSite@imgur ] }
    - { outbound: Dev, rule_set: [ GeoSite@category-dev ] }
    - { outbound: SSH@22, port: [ 22 ] }
    - { outbound: 默认, rule_set: [ GeoSite@tiktok, GeoSite@meta, GeoSite@category-anticensorship, GeoSite@category-games, GeoSite@category-social-media-!cn, GeoSite@category-porn, GeoSite@category-communication ] }

    - { outbound: 国内, rule_set: [ GeoSite@tld-cn, GeoSite@cn ] }
    - { outbound: 默认, rule_set: [ GeoSite@tld-!cn, GeoSite@gfw, GeoSite@geolocation-!cn ] }

    - { outbound: DIRECT, rule_set: [ GeoIP@private ] }
    - { outbound: 国内, rule_set: [ GeoIP@cn ] }
    - { outbound: Google, rule_set: [ GeoIP@google ] }


experimental:
  cache_file: { enabled: true }
  clash_api: { external_controller: 127.0.0.1:9090 }


outbounds:
  - { tag: 默认, type: selector, outbounds: [ 自动选择, 手动选择1, 手动选择2, 手动选择3, 香港节点, 台湾节点, 日本节点, 新加坡节点, 美国节点, DIRECT ], interrupt_exist_connections: true }
  - { tag: 自动选择, type: urltest, include-all: true, filter: '^(?!.*(?:(中国|CN))).*', interrupt_exist_connections: true, url: https://www.youtube.com/generate_204, interval: 6h, idle_timeout: 12h }
  - { tag: '⭕⭕====分割线 1====⭕⭕', type: selector, outbounds: [ DIRECT ] }
  - { tag: 手动选择1, type: selector, outbounds: [ 自动选择, 香港节点, 台湾节点, 日本节点, 新加坡节点, 美国节点, DIRECT ], interrupt_exist_connections: true }
  - { tag: 手动选择2, type: selector, include-all: true, interrupt_exist_connections: true }
  - { tag: 手动选择3, type: selector, include-all: true, interrupt_exist_connections: true }
  - { tag: 前置代理组, type: selector, include-all-providers: true, interrupt_exist_connections: true }
  - { tag: '⭕⭕====分割线 2====⭕⭕', type: selector, outbounds: [ DIRECT ] }
  - { tag: Google, outbounds: [ 默认, 香港节点, 台湾节点, 日本节点, 新加坡节点, 美国节点, 手动选择1, 手动选择2, 手动选择3, 自动选择, DIRECT ], type: selector, interrupt_exist_connections: true }
  - { tag: Microsoft, outbounds: [ 默认, 香港节点, 台湾节点, 日本节点, 新加坡节点, 美国节点, 手动选择1, 手动选择2, 手动选择3, 自动选择, DIRECT ], type: selector, interrupt_exist_connections: true }
  - { tag: Zoom, outbounds: [ 默认, 香港节点, 台湾节点, 日本节点, 新加坡节点, 美国节点, 手动选择1, 手动选择2, 手动选择3, 自动选择, DIRECT ], type: selector, interrupt_exist_connections: true }
  - { tag: Apple, outbounds: [ DIRECT, 默认, 香港节点, 台湾节点, 日本节点, 新加坡节点, 美国节点, 手动选择1, 手动选择2, 手动选择3, 自动选择 ], type: selector, interrupt_exist_connections: true }
  - { tag: LLM, outbounds: [ 默认, 香港节点, 台湾节点, 日本节点, 新加坡节点, 美国节点, 手动选择1, 手动选择2, 手动选择3, 自动选择, DIRECT ], type: selector, interrupt_exist_connections: true }
  - { tag: Dev, outbounds: [ 默认, 香港节点, 台湾节点, 日本节点, 新加坡节点, 美国节点, 手动选择1, 手动选择2, 手动选择3, 自动选择, DIRECT ], type: selector, interrupt_exist_connections: true }
  - { tag: 国外图床, outbounds: [ 默认, 香港节点, 台湾节点, 日本节点, 新加坡节点, 美国节点, 手动选择1, 手动选择2, 手动选择3, 自动选择, DIRECT ], type: selector, interrupt_exist_connections: true }
  - { tag: SSH@22, outbounds: [ 默认, 香港节点, 台湾节点, 日本节点, 新加坡节点, 美国节点, 手动选择1, 手动选择2, 手动选择3, 自动选择, DIRECT ], type: selector, interrupt_exist_connections: true }
  - { tag: GoogleOneVPNCheckPoint, outbounds: [ 默认, 香港节点, 台湾节点, 日本节点, 新加坡节点, 美国节点, 手动选择1, 手动选择2, 手动选择3, 自动选择, DIRECT ], type: selector, interrupt_exist_connections: true }
  - { tag: GoogleOneVPNTun, outbounds: [ 默认, 香港节点, 台湾节点, 日本节点, 新加坡节点, 美国节点, 手动选择1, 手动选择2, 手动选择3, 自动选择, DIRECT ], type: selector, interrupt_exist_connections: true }
  - { tag: '⭕⭕====分割线 3====⭕⭕', type: selector, outbounds: [ DIRECT ] }
  - { tag: 香港节点, type: urltest, include-all-providers: true, filter: '(香港)', interrupt_exist_connections: true, url: https://www.youtube.com/generate_204, interval: 6h, idle_timeout: 12h }
  - { tag: 台湾节点, type: urltest, include-all-providers: true, filter: '(台湾)', interrupt_exist_connections: true, url: https://www.youtube.com/generate_204, interval: 6h, idle_timeout: 12h }
  - { tag: 日本节点, type: urltest, include-all-providers: true, filter: '(日本)', interrupt_exist_connections: true, url: https://www.youtube.com/generate_204, interval: 6h, idle_timeout: 12h }
  - { tag: 新加坡节点, type: urltest, include-all-providers: true, filter: '(新加坡)', interrupt_exist_connections: true, url: https://www.youtube.com/generate_204, interval: 6h, idle_timeout: 12h }
  - { tag: 美国节点, type: urltest, include-all-providers: true, filter: '美|us|unitedstates|united states', interrupt_exist_connections: true, url: https://www.youtube.com/generate_204, interval: 6h, idle_timeout: 12h }
  - { tag: '⭕⭕====分割线 4====⭕⭕', type: selector, outbounds: [ DIRECT ] }
  - { tag: 国内, outbounds: [ DIRECT, 默认, 香港节点, 台湾节点, 日本节点, 新加坡节点, 美国节点, 手动选择1, 手动选择2, 手动选择3, 自动选择 ], type: selector, interrupt_exist_connections: true }

  - { tag: DIRECT, type: direct }
  - { tag: dns-out, type: dns }

custom_outbounds:
  - tag: G1 ss detour
    type: shadowsocks
    server: 149.104.24.100
    server_port: 10001
    method: chacha20-ietf-poly1305
    password: aaf0cc77-ec05-4b5e-8fbb-8919c3aecf8c
    multiplex: { enabled: true }
    detour: 前置代理组
  - tag: G1 ss
    type: shadowsocks
    server: 149.104.24.100
    server_port: 10001
    method: chacha20-ietf-poly1305
    password: aaf0cc77-ec05-4b5e-8fbb-8919c3aecf8c
    multiplex: { enabled: true }
