log:
  level: info
  timestamp: true

experimental:
  cache_file: { enabled: true }
  clash_api:
    external_controller: 127.0.0.1:9090

dns:
  final: remote
  strategy: ipv4_only # 这里 prefer_ipv4 大概率拉不下 rulesets，报错提示 exchange fail
  servers:
    - { tag: remote, address: https://8.8.8.8/dns-query, detour: 默认 }
    - { tag: local, address: https://223.5.5.5/dns-query, detour: DIRECT }
  rules:
    - { server: local, rule_set: [ MainlandNetwork, GeoSite@private, GeoSite@cn ] }
    - { server: local, outbound: [ any ] }


route:
  final: 默认
  auto_detect_interface: true
  rule_set:
    - { tag: MainlandNetwork, download_detour: DIRECT, type: remote, format: source, url: https://fastly.jsdelivr.net/gh/eric-gitta-moore/sub-rules-provider@main/rule/james-curtis/Clash/Providers/MainlandNetwork.json }
    - { tag: AboardNetwork, download_detour: DIRECT, type: remote, format: source, url: https://fastly.jsdelivr.net/gh/eric-gitta-moore/sub-rules-provider@main/rule/james-curtis/Clash/Providers/AboardNetwork.json }

    - { tag: GeoSite@private, download_detour: DIRECT, type: remote, format: binary, url: https://fastly.jsdelivr.net/gh/eric-gitta-moore/meta-rules-dat@sing/geo/geosite/private.srs }
    - { tag: GeoSite@cn, download_detour: DIRECT, type: remote, format: binary, url: https://fastly.jsdelivr.net/gh/eric-gitta-moore/meta-rules-dat@sing/geo/geosite/cn.srs }
    - { tag: GeoIP@private, download_detour: DIRECT, type: remote, format: binary, url: https://fastly.jsdelivr.net/gh/eric-gitta-moore/meta-rules-dat@sing/geo/geoip/private.srs }
    - { tag: GeoIP@cn, download_detour: DIRECT, type: remote, format: binary, url: https://fastly.jsdelivr.net/gh/eric-gitta-moore/meta-rules-dat@sing/geo/geoip/cn.srs }

  rules:
    - { outbound: dns-out, protocol: dns }
    - { outbound: DIRECT, process_name: [ "sunshine.exe", "sunshinesvc.exe", "SunloginClient.exe", "ToDesk.exe", "RayLink.exe" ] }

    - { outbound: G1VCheckPoint, domain_suffix: [ ".cloud.cupronickel.goog" ], domain_keyword: [ "-pa.googleapis.com" ] }

    - { outbound: 默认, rule_set: [ AboardNetwork ] }
    - { outbound: 国内, rule_set: [ MainlandNetwork, GeoSite@private, GeoSite@cn, GeoIP@private, GeoIP@cn ] }


outbounds:
  - { tag: 默认, type: selector, outbounds: [ 自动选择, 手动选择, 落地代理, DIRECT ] }
  - { tag: 自动选择, type: urltest, url: https://www.google.com/generate_204, interval: 4h, idle_timeout: 8h }
  - { tag: 手动选择, type: selector, outbounds: [] }
  - { tag: 落地前置, type: selector, outbounds: [] }
  - { tag: 落地代理, type: selector, outbounds: [] }
  - { tag: G1VCheckPoint, outbounds: [ 默认, 手动选择, DIRECT ], type: selector }
  - { tag: 国内, type: selector, outbounds: [ DIRECT, 默认, 自动选择, 手动选择, 落地代理 ] }

  - { tag: DIRECT, type: direct }
  - { tag: dns-out, type: dns }


inbounds:
  - type: mixed
    tag: mixed-in
    listen: 127.0.0.1
    listen_port: 2080
    sniff: true
    sniff_override_destination: true
    domain_strategy: prefer_ipv4

