log:
  level: debug
  timestamp: true


dns:
  servers:
    - {tag: dns_direct, address: h3://dns.alidns.com/dns-query, address_resolver: dns_resolver, detour: DIRECT}
    - {tag: dns_resolver, address: 223.5.5.5, detour: DIRECT}
    - {tag: dns_proxy, address: tls://1.1.1.1, address_resolver: dns_resolver}
  rules:
    - {outbound: [any], server: dns_resolver}
    - {rule_set: [geolocation-!cn, gfw, tld-!cn], server: dns_proxy}
  final: dns_direct
  independent_cache: true

ntp:
  enabled: true
  server: time.apple.com
  server_port: 123
  interval: 30m
  detour: DIRECT


inbounds:
  - type: mixed
    tag: mixed-in
    listen: 0.0.0.0
    listen_port: 2080
  - type: tun
    tag: tun-in
    inet4_address: 172.19.0.1/30
    inet6_address: fdfe:dcba:9876::1/126
    auto_route: true
    strict_route: true
    stack: mixed
    sniff: true

route:
  rule_set:
    - {tag: AboardNetwork, type: remote, format: source, download_detour: direct, url: https://raw.githubusercontent.com/james-curtis/sub-diversion-rules/main/rule/james-curtis/Clash/Providers/AboardNetwork.yaml}
    - {tag: CN, type: remote, format: source, download_detour: direct, url: https://raw.githubusercontent.com/james-curtis/sub-diversion-rules/main/rule/james-curtis/Clash/Providers/CN.yaml}
    - {tag: TikTok, type: remote, format: source, download_detour: direct, url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.yaml}
    - {tag: LLM, type: remote, format: source, download_detour: direct, url: https://raw.githubusercontent.com/james-curtis/sub-diversion-rules/main/rule/james-curtis/Clash/Providers/LLM.yaml}
    # 系统规则 begin
    - {tag: GeoSite@category-dev-cn, type: remote, format: binary, download_detour: direct, url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/category-dev-cn.srs}
    - {tag: GeoSite@category-scholar-cn, type: remote, format: binary, download_detour: direct, url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/category-scholar-cn.srs}
    - {tag: GeoSite@category-games@cn, type: remote, format: binary, download_detour: direct, url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/category-games@cn.srs}
    - {tag: GeoSite@google@cn, type: remote, format: binary, download_detour: direct, url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/google@cn.srs}
    - {tag: GeoSite@tld-cn, type: remote, format: binary, download_detour: direct, url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/tld-cn.srs}
    - {tag: GeoSite@cn, type: remote, format: binary, download_detour: direct, url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/cn.srs}

    - {tag: GeoSite@apple, type: remote, format: binary, download_detour: direct, url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/apple.srs}
    - {tag: GeoSite@zoom, type: remote, format: binary, download_detour: direct, url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/zoom.srs}
    - {tag: GeoSite@google, type: remote, format: binary, download_detour: direct, url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/google.srs}
    - {tag: GeoSite@meta, type: remote, format: binary, download_detour: direct, url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/meta.srs}
    - {tag: GeoSite@category-games, type: remote, format: binary, download_detour: direct, url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/category-games.srs}

    - {tag: GeoSite@category-social-media-!cn, type: remote, format: binary, download_detour: direct, url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/category-social-media-!cn.srs}
    - {tag: GeoSite@category-porn, type: remote, format: binary, download_detour: direct, url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/category-porn.srs}
    - {tag: GeoSite@category-communication, type: remote, format: binary, download_detour: direct, url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/category-communication.srs}
    - {tag: GeoSite@category-dev, type: remote, format: binary, download_detour: direct, url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/category-dev.srs}

    - {tag: GeoSite@tld-!cn, type: remote, format: binary, download_detour: direct, url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/tld-!cn.srs}
    - {tag: GeoSite@gfw, type: remote, format: binary, download_detour: direct, url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/gfw.srs}
    - {tag: GeoSite@geolocation-!cn, type: remote, format: binary, download_detour: direct, url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/geolocation-!cn.srs}

    - {tag: GeoIP@google, type: remote, format: binary, download_detour: direct, url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geoip/google.srs}
    - {tag: GeoIP@cn, type: remote, format: binary, download_detour: direct, url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geoip/cn.srs}
    - {tag: GeoMixed@private, type: remote, format: binary, download_detour: direct, url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/mixed/private.srs}
  # 系统规则 end

  rules:
    - outbound: direct
      rule_set: [AboardNetwork]
    - outbound: 国内
      rule_set: [CN]


experimental:
  cache_file:
    enabled: true


outbounds:
  - tag: G1 ss
    type: shadowsocks
    server: 149.104.24.100
    server_port: 10001
    method: chacha20-ietf-poly1305
    password: aaf0cc77-ec05-4b5e-8fbb-8919c3aecf8c
    multiplex:
      enabled: true