dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  default-nameserver:
    - 223.5.5.5 # aliyun
    - 119.29.29.29 # tencent
    - 101.226.4.6 # 360

  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.360.cn/dns-query
    - https://doh.pub/dns-query
  fallback:
    - tls://8.8.4.4
    - tls://1.1.1.1
    - https://dns.google/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true

rule-providers:
  MainlandNetwork:
    type: http
    url: https://fastly.jsdelivr.net/gh/eric-gitta-moore/sub-rules-provider@main/rule/james-curtis/Clash/Providers/MainlandNetwork.yaml
    proxy: DIRECT
    behavior: classical
  AboardNetwork:
    type: http
    url: https://fastly.jsdelivr.net/gh/eric-gitta-moore/sub-rules-provider@main/rule/james-curtis/Clash/Providers/AboardNetwork.yaml
    proxy: DIRECT
    behavior: classical
  
rules:
  - GEOSITE,private,DIRECT
  - GEOIP,private,国内

  - RULE-SET,AboardNetwork,漏网之鱼
  - RULE-SET,MainlandNetwork,国内

  - GEOSITE,cn,国内
  - GEOIP,cn,国内

  - AND,(DST-PORT,443),(NETWORK,UDP),REJECT # quic
  - MATCH,漏网之鱼
