dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
  proxy-server-nameserver:
    - https://223.5.5.5/dns-query
    - https://1.12.12.12/dns-query
sniffer:
  enable: true
  sniff:
    TLS:
      ports: [ 443, 8443 ]
    HTTP:
      ports: [ 80, 8080-8880 ]


rules:
  - RULE-SET,LocalAreaNetwork,DIRECT
  - RULE-SET,AboardNetwork,漏网之鱼

  - AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(GEOSITE,geolocation-!cn),REJECT # quic
  - GEOSITE,google@cn,国内

  - AND,((DOMAIN-SUFFIX,github.com),(DST-PORT,22)),Abroad SSH
  - GEOSITE,youtube,YouTube
  - GEOSITE,twitter,Twitter
  - GEOSITE,facebook,Facebook
  - GEOSITE,openai,OpenAI
  - GEOSITE,github,GitHub
  - GEOSITE,onedrive,OneDrive
  - GEOSITE,xbox,Xbox
  - GEOSITE,apple,Apple
  - GEOSITE,zoom,Zoom
  - GEOSITE,microsoft,Microsoft
  - GEOSITE,netflix,NETFLIX
  - RULE-SET,TikTok,TikTok
  - GEOSITE,category-scholar-!cn,Scholar
  - GEOSITE,jetbrains,JetBrains
  - GEOSITE,category-dev,Dev
  - RULE-SET,GoogleOneVPN,GoogleOneVPN

  - GEOSITE,category-games@cn,国内
  - GEOSITE,google,Google
  - GEOSITE,aws,AWS
  - GEOSITE,cn,国内
  - GEOSITE,geolocation-!cn,漏网之鱼

  - GEOIP,google,Google
  - GEOIP,netflix,NETFLIX
  - GEOIP,cn,国内
  - DST-PORT,22,Abroad SSH
  - MATCH,漏网之鱼