dns:
  enable: true
  prefer-h3: true
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  default-nameserver:
    - 223.5.5.5 # aliyun
    - 119.29.29.29 # tencent
    - 101.226.4.6 # 360

  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.360.cn/dns-query
    - https://doh.pub/dns-query
  fallback:
    - tls://8.8.4.4
    - tls://1.1.1.1
  #    - https://cloudflare-dns.com/dns-query
  #    - https://dns.google/dns-query
  #    - https://doh.opendns.com/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
      - geolocation-!cn
    ipcidr:
      - 240.0.0.0/4
    domain:
      - "+.google.com"
      - "+.facebook.com"
      - "+.youtube.com"

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]

rules:
  - GEOSITE,private,DIRECT
  - RULE-SET,AboardNetwork,漏网之鱼
  - RULE-SET,CN,国内

  - AND,(DST-PORT,443),(NETWORK,UDP),REJECT # quic

  - GEOSITE,apple,Apple

  - GEOSITE,category-dev-cn,国内
  - GEOSITE,category-scholar-cn,国内
  - GEOSITE,category-games@cn,国内
  - GEOSITE,google@cn,国内
  - GEOSITE,tld-cn,国内
  - GEOSITE,cn,国内

  - RULE-SET,LLM,LLM
  - GEOSITE,zoom,Zoom

  - GEOSITE,google,Google
  - GEOSITE,meta,漏网之鱼
  - GEOSITE,category-social-media-!cn,漏网之鱼
  - GEOSITE,category-porn,漏网之鱼
  - GEOSITE,category-communication,漏网之鱼
  - GEOSITE,tld-!cn,漏网之鱼
  - GEOSITE,gfw,漏网之鱼
  - GEOSITE,geolocation-!cn,漏网之鱼

  - GEOIP,google,Google
  - GEOIP,cn,国内

  - MATCH,漏网之鱼
