dns:
  enable: true
  prefer-h3: true
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  default-nameserver:
    - 223.5.5.5 # aliyun
    - 119.29.29.29 # tencent
    - 101.226.4.6 # 360

  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.360.cn/dns-query
    - https://doh.pub/dns-query
  fallback:
    - tls://8.8.4.4
    - tls://1.1.1.1
  #    - https://cloudflare-dns.com/dns-query
  #    - https://dns.google/dns-query
  #    - https://doh.opendns.com/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
      - geolocation-!cn
    ipcidr:
      - 240.0.0.0/4
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [ 80, 8080-8880 ]
    TLS:
      ports: [ 443, 8443 ]
    QUIC:
      ports: [ 443, 8443 ]


rules:
  - RULE-SET,LocalAreaNetwork,DIRECT
  - GEOSITE,private,DIRECT
  - RULE-SET,AboardNetwork,漏网之鱼

  #  - AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(GEOSITE,youtube),REJECT # youtube quic
  - GEOSITE,google@cn,国内

  - AND,((DOMAIN-SUFFIX,github.com),(DST-PORT,22)),Abroad SSH
  - GEOSITE,youtube,YouTube
  - GEOSITE,twitter,Twitter
  - GEOSITE,facebook,Facebook
  - GEOSITE,openai,OpenAI
  - GEOSITE,github,GitHub
  - GEOSITE,onedrive,OneDrive
  - GEOSITE,xbox,Xbox
  - GEOSITE,apple,Apple
  - GEOSITE,zoom,Zoom
  - GEOSITE,microsoft,Microsoft
  - GEOSITE,netflix,NETFLIX
  - RULE-SET,TikTok,TikTok
  - GEOSITE,category-scholar-!cn,Scholar
  - GEOSITE,jetbrains,JetBrains
  - GEOSITE,category-dev,Dev
  - RULE-SET,GoogleOneVPNTun,GoogleOneVPNTun
  - RULE-SET,GoogleOneVPNCheckPoint,GoogleOneVPNCheckPoint

  - GEOSITE,category-games@cn,国内
  - GEOSITE,google,Google
  - GEOSITE,aws,AWS
  - GEOSITE,cn,国内
  - GEOSITE,gfw,漏网之鱼
  - GEOSITE,geolocation-!cn,漏网之鱼

  - GEOIP,google,Google,no-resolve
  - GEOIP,netflix,NETFLIX,no-resolve
  - GEOIP,cn,国内,no-resolve
  - DST-PORT,22,Abroad SSH
  - MATCH,漏网之鱼